version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app
    overwrite: true
permissions:
  - object: /home/ec2-user/flask-app/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
